version: '3.3'

services:

  metricbeat:
    #image: docker.elastic.co/beats/metricbeat-oss:8.9.1-arm64
    image: docker.elastic.co/beats/metricbeat-oss:8.9.1-amd64
    container_name: metricbeat
    volumes:
      - ./conf/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./output:/output
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    user: root
    command: ["--strict.perms=false"]

  compressor:
    build: ./compressor
    container_name: compressor
    volumes:
      - ./output:/output
    user: root
    command: ["--input", "/output"]
    environment:
      - PYTHONUNBUFFERED=1